version: "3.4"

services:
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: delliv
        POSTGRES_USER: user-delliv
        POSTGRES_DB: delliv-db
      ports:
        - 5432:5432

  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: ./challenge-delliv-backend
      dockerfile: Dockerfile.back
    ports:
      - 3003:3003
    networks:
      - app_network
    depends_on:
      - db
    environment:
      - DATABASE_URL="postgres://user-delliv:delliv@localhost:5432/delliv-db"
      - SECRET_JWT=123456
    restart: unless-stopped

  frontend:
    build:
      dockerfile: Dockerfile.front
      context: ./challenge-delliv-front
    volumes:
      - /app/node_modules
      - ./frontend/web:/app
    ports:
        - 3000:3000

networks:
  app_network:
    driver: bridge