version: "3.8"

services:
  db:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_PASSWORD: delliv
        POSTGRES_USER: user-delliv
        POSTGRES_DB: delliv-db
      ports:
        - "5432:5432"
      volumes:
        - postgres:/var/lib/postgresql/data

  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: ./challenge-delliv-backend
      dockerfile: Dockerfile.back
    environment:
      DATABASE_URL: "postgres://user-delliv:delliv@db:5432/delliv-db?schema=public"
      SECRET_JWT: 123456
    ports:
      - 3003:3003
    networks:
      - app_network
    depends_on:
      - db
    links: 
      - db
    restart: unless-stopped

  frontend:
    build:
      dockerfile: Dockerfile.front
      context: ./challenge-delliv-front
    volumes:
      - /app/node_modules
      - ./frontend/web:/app
    ports:
        - 3000:3000

networks:
  app_network:
    driver: bridge

volumes:
  postgres: