version: "3.4"

services:
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: delliv
        POSTGRES_USER: user-delliv
        POSTGRES_DB: delliv-db
      ports:
        - 5432:5432
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 8080:80
  backend:
    build:
      dockerfile: Dockerfile
      context: ./challenge-delliv-backend
    volumes:
      - /app/node_modules
      - ./backend:/app
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./challenge-delliv-front
    volumes:
      - /app/node_modules
      - ./frontend/web:/app