version: "3.4"

services:
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: delliv
        POSTGRES_USER: user-delliv
        POSTGRES_DB: delliv-db
      ports:
        - 5432:5432
  challenge-delliv-backend:
    build:
      dockerfile: Dockerfile
      context: ./challenge-delliv-backend
    ports:
      - 5000:5000
    networks:
      - app_network
    depends_on:
      - db

  challenge-delliv-front:
    build:
      dockerfile: Dockerfile
      context: ./challenge-delliv-front
    volumes:
      - /app/node_modules
      - ./challenge-delliv-front/web:/app

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - challenge-delliv-backend
      - challenge-delliv-front
    networks:
      - app_network

volumes:
    build_front:
    pg:

networks:
    app_network:
        driver: bridge