FROM node:18-alpine AS development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install glob rimraf

RUN npm install --only=development

COPY . .

RUN yarn run prisma generate
RUN yarn build


FROM node:18-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --only=production

COPY . .

RUN yarn run prisma generate
RUN yarn build

COPY --from=development /usr/src/app/dist ./dist

CMD ["yarn", "start"]
