#version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: delliv
      POSTGRES_USER: user-delliv
      POSTGRES_DB: delliv-db
    ports:
      - 5432:5432
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile.back
      command: npm run start:dev
    ports:
      - 3000:3000
      - 3001:9229
    networks:
      - nesjs-network
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  # backend:
  #   build:
  #     dockerfile: Dockerfile.back
  #     context: ./
  #   volumes:
  #     - /root/challenge-delliv/challenge-delliv-backend/backend:/app
  #     - /root/challenge-delliv/challenge-delliv-backend/backend/app/node_modules
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile.back
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
    nesjs-network:
      driver: bridge