FROM node:18-alpine

ENV NODE_ENV=production

RUN yarn global add typescript

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

RUN yarn build

COPY . .

EXPOSE 3003 

CMD [ "yarn", "start" ]